### PR TITLE
Added LDAP data handling to devices and reader queries; Updated styling from .2f to .1f

### PR DESCRIPTION
**Pull request by IreneFlorez**

### CODE REVIEW

**Comment by jenniferwang-wmf** [comment]
Resolved conflicts. Merge Irene's change.

**Comment by nshahquinn** [comment]
Hmm, looks like this didn't actually get merged?

**Comment by nshahquinn** [comment]
There we go!

**Comment by nshahquinn** [comment]
@jenniferwang-wmf thanks for handling the merge conflicts! With that done, pressing the button was very easy 😊

**Pull request merged**
